# Generated by Django 5.2.4 on 2025-07-30 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codice_isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=255)),
                ('anno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('codice', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ricetta',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('titolo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('antipasto', 'Antipasto'), ('primo', 'Primo'), ('secondo', 'Secondo'), ('contorno', 'Contorno'), ('dessert', 'Dessert')], max_length=20)),
                ('preparazione', models.TextField(blank=True, null=True)),
                ('tempo_preparazione', models.IntegerField(blank=True, null=True)),
                ('difficolta', models.CharField(blank=True, max_length=50, null=True)),
                ('voto_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.IntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagine', to='ricettario.libro')),
            ],
            options={
                'unique_together': {('libro', 'numero_pagina')},
            },
        ),
        migrations.CreateModel(
            name='RicettaRegionale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricettario.regione')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricettario.ricetta')),
            ],
            options={
                'unique_together': {('regione', 'ricetta')},
            },
        ),
        migrations.AddField(
            model_name='ricetta',
            name='regioni',
            field=models.ManyToManyField(through='ricettario.RicettaRegionale', to='ricettario.regione'),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_progressivo', models.IntegerField()),
                ('ingrediente', models.CharField(max_length=100)),
                ('quantita', models.CharField(max_length=50)),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredienti', to='ricettario.ricetta')),
            ],
            options={
                'unique_together': {('ricetta', 'numero_progressivo')},
            },
        ),
        migrations.CreateModel(
            name='RicettaPubblicata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricettario.pagina')),
                ('ricetta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ricettario.ricetta')),
            ],
            options={
                'unique_together': {('ricetta', 'pagina')},
            },
        ),
    ]
